### ISSUE TITLE
Developing of this repo / Weiterentwicklung dieser Repo

### ISSUE THREAD

**Issue by Jhogece** [GymWenFLL/tpp_helper_scripts_for_repo#1]
Should we develop this repo further or deprecate it?
Sollen wir diese Repo weiterentwickeln oder nicht?

**Comment by yoyo13** [comment]
nope :)

**Comment by xFLLSquadronNorden** [comment]
yeah i will FUCKING DO IT!!!! JUSD DU ID!!1!1!!
